---
language: ruby
rvm:
  - "2.6"

env:
  global:
    - RAILS_ENV: test

before_script:
  - bin/rails server -d
  - rake db:create
  - rake db:schema:load

  - |
    attempt_counter=0
    max_attempts=6
    until $(curl --output /dev/null --silent -k --head http://localhost:3000/); do
      if [ ${attempt_counter} -eq ${max_attempts} ];then
        echo "Timeout occurred while waiting for app to start."
        exit 1
      fi

      printf '.'
      attempt_counter=$(($attempt_counter+1))
      sleep 10
    done

script:
  - curl --head http://localhost:3000/
