---
language: ruby
rvm:
  - "2.6"

env:
  global:
    - RAILS_ENV: test

before_script:
  - bin/rails server -d
  - bundle exec rake db:create
  - bundle exec rake db:schema:load

  # Copy the CI secrets.yml file.
  - cp test/secrets.ci.yml config/secrets.yml
  - chmod 777 config/secrets.yml

script:
  - curl --fail --head http://localhost:3000/

after_failure:
  - curl http://localhost:3000/
  - cat config/secrets.yml
