---
language: ruby
rvm:
  - "2.6"

env:
  global:
    - RAILS_ENV: test

before_script:
  - bin/rails server -d
  - rake db:create
  - rake db:schema:load

script:
  - curl --fail --head http://localhost:3000/

after_failure:
  - curl http://localhost:3000/
